# Generated by Django 3.2.5 on 2023-06-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0002_alter_inspireuser_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspireuser',
            name='pwcode',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspireuser',
            name='pwcodecreated',
            field=models.DateField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
