# Generated by Django 3.2.5 on 2023-06-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0003_auto_20230606_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspireuser',
            name='pwcode',
        ),
        migrations.RemoveField(
            model_name='inspireuser',
            name='pwcodecreated',
        ),
    ]
