# Generated by Django 3.2.5 on 2023-06-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0004_auto_20230606_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspireuser',
            name='pwcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspireuser',
            name='pwcodecreated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
