# Generated by Django 3.2.5 on 2023-06-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0006_alter_inspireuser_pwcodecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspireuser',
            name='emailverified',
            field=models.BooleanField(default=False),
        ),
    ]
