# Generated by Django 3.2.5 on 2023-06-12 01:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0008_alter_inspireuser_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspireuser',
            name='favourites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
