# Generated by Django 3.2.5 on 2023-06-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0010_inspireuser_rememberme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspireuser',
            name='rememberme',
        ),
    ]
