# Generated by Django 3.2.5 on 2023-06-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0011_remove_inspireuser_rememberme'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspireuser',
            name='lastusername',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
