# Generated by Django 3.2.5 on 2023-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0012_inspireuser_lastusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspireuser',
            name='lastusername',
        ),
        migrations.AddField(
            model_name='inspireuser',
            name='lastemailchange',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inspireuser',
            name='lastpwchange',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inspireuser',
            name='lastunchange',
            field=models.DateTimeField(null=True),
        ),
    ]
