# Generated by Django 3.2.5 on 2023-06-22 01:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0015_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('created', models.DateTimeField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('src', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
