# Generated by Django 3.2.5 on 2023-06-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0017_auto_20230622_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.TextField(default='n/a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='n/a', max_length=1000),
            preserve_default=False,
        ),
    ]
