# Generated by Django 3.2.5 on 2023-06-22 02:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0018_auto_20230622_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspireuser',
            name='checkednotifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inspireuser',
            name='notifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='text',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
