# Generated by Django 3.2.5 on 2023-06-23 17:18

from django.db import migrations, models
from datetime import datetime
import pytz


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0020_auto_20230623_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent',
            field=models.DateTimeField(default=datetime.now(pytz.utc)),
            preserve_default=False,
        ),
    ]
