# Generated by Django 3.2.5 on 2023-06-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0023_auto_20230624_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
