# Generated by Django 3.2.5 on 2023-06-28 01:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0025_auto_20230626_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspireuser',
            old_name='favourites',
            new_name='textfavourites',
        ),
        migrations.AddField(
            model_name='inspireuser',
            name='videofavourites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
