# Generated by Django 3.2.5 on 2023-06-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0026_auto_20230628_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('postid', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='inspireuser',
            old_name='textfavourites',
            new_name='favourites',
        ),
        migrations.RemoveField(
            model_name='inspireuser',
            name='videofavourites',
        ),
    ]
