# Generated by Django 3.2.5 on 2023-07-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0027_auto_20230630_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='postid',
            field=models.CharField(default='aaa', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='postid',
            field=models.CharField(default='aaa', max_length=10),
            preserve_default=False,
        ),
    ]
