# Generated by Django 3.2.5 on 2023-07-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0028_auto_20230702_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='postid',
            field=models.CharField(max_length=10),
        ),
    ]
