# Generated by Django 3.2.5 on 2023-07-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0029_alter_favourite_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tn',
            field=models.CharField(default='google.com', max_length=200),
            preserve_default=False,
        ),
    ]
