# Generated by Django 3.2.5 on 2023-07-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0031_remove_video_tn'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
