# Generated by Django 3.2.5 on 2023-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0035_auto_20230722_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='postsize',
            field=models.CharField(default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='postsize',
            field=models.CharField(default='medium', max_length=50),
        ),
    ]
